 import './globals.css'
import './flags.css';
import React from 'react';
import ReactDOM from 'react-dom/client';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/lara-light-indigo/theme.css';   // theme
import 'primeflex/primeflex.css';                                   // css utility
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.css';   
import type { Metadata } from 'next'
import { Akaya_Kanadaka, Inter } from 'next/font/google'
import Header from '../components/header'
import { join } from 'path'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header/> */}
        <div className=''>
          {children}
        </div>
      </body>
    </html>
  )
}
